# --- Start Minikube ---
- name: Delete minikube
  command: minikube delete

- name: Start minikube
  command: minikube start

# --- Repo ---
- name: Remove repo if exists
  file:
    path: "{{ repo_dest }}"
    state: absent

- name: Clone repo
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    version: HEAD

# --- Ingress Nginx Controller ---
- name: Enable nginx ingress addon
  command: minikube addons enable ingress

- name: Wait for ingress controller
  command: kubectl rollout status deployment/ingress-nginx-controller -n ingress-nginx

- name: Apply ingress
  command: kubectl apply -f {{ manifests_path }}/{{ ingress_file }}

# --- Applying Manifests ---
- name: Apply manifests for infrastructure
  command: kubectl apply -f {{ manifests_path }}/{{ item }}
  loop: "{{ infra }}"
  loop_control:
    label: "{{ item }}"

- name: Apply manifests for services
  command: kubectl apply -f {{ manifests_services_path }}/{{ item }}
  loop: "{{ services }}"
  loop_control:
    label: "{{ item }}"
