repo_url: "https://github.com/Tehno-R/ural-deploy.git"
repo_dest: "/repo"
k8s_path: "{{ repo_dest }}/minikube"   # где лежат манифесты
ingress_file: "ingress.yaml"

k8s_manifests:
  - namespace.yaml
  - postgres-secret.yaml
  - postgresql-deployment.yaml
  - redis-deployment.yaml
  - kafka-deployment.yaml
