repo_url: "https://github.com/Tehno-R/ural-deploy.git"
repo_dest: "~/repo"
manifests_path: "{{ repo_dest }}/minikube"   # manifests place
manifests_services_path: "{{ repo_dest }}/minikube/services"
manifests_observability_path: "{{ repo_dest }}/minikube/observability"
ingress_file: "ingress.yaml"

infra:
  - namespace.yaml
  - postgres-secret.yaml
  - postgresql-deployment.yaml
  - redis-deployment.yaml
  - kafka-deployment.yaml

services:
  - ural-aggregator-deployment
  - ural-gai-deployment
  - ural-cars-deployment
  - ural-cargo-deployment
  - ural-contracts-deployment
  - ural-users-deployment
  - ural-auth-deployment
  - ural-front-deployment

monitoring:
  - prometheus-deployment