repo_url: "https://github.com/Tehno-R/ural-deploy.git"
repo_dest: "~/repo"
manifests_path: "{{ repo_dest }}/minikube"   # manifests place
manifests_services_path: "{{ repo_dest }}/minikube/services"
manifests_observability_path: "{{ repo_dest }}/minikube/observability"
ingress_file: "ingress.yaml"
headlamp_port: "32520"
recreate: "false"

infra:
  - namespace.yaml
  - postgres-secret.yaml
  - postgresql-deployment.yaml
  - redis-deployment.yaml
  - kafka-deployment.yaml

services:
  - ural-aggregator-deployment.yaml
  - ural-gai-deployment.yaml
  - ural-cars-deployment.yaml
  - ural-cargo-deployment.yaml
  - ural-contracts-deployment.yaml
  - ural-users-deployment.yaml
  - ural-auth-deployment.yaml
  - ural-front-deployment.yaml

monitoring:
  - node-exporter-daemonset.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml